### PR TITLE
Adding button to toggle Announce block

### PR DESCRIPTION
**Pull request by Andygol**
This pull request introduces a button that allows toggling the Announce block, closely replicating the same button found on the original welcome.osm.org website. (Solution provided by @kamilkrzyskow in https://github.com/squidfunk/mkdocs-material/discussions/6097#discussioncomment-7200178)

See ℹ️ icon new day/night switcher

image

Closes issue: #5

### CODE REVIEW

**Comment by kamilkrzyskow** [comment]
Oh, I see that you're using the built-in announce dismiss X button. It doesn't reset the state of the new toggle buttons.
I will think about a clean solution for this, because I assume that simply adding another event listener as is would create some weird race condition.

**Comment by Andygol** [comment]
I had an idea to create a completely new Info block component (along with a toggle button) that mimics the behavior of the Consent block, but without storing information in a cookie.  Unfortunately, I currently do not have the appropriate qualifications to handle this on my own.

But your suggestion as a workaround seems to work now. 

In case you have some spare time and desire, your help will be highly appreciated.

**Comment by kamilkrzyskow** [comment]
You're saying you want a sort of "floating overlay" for the page, which you can toggle with some sort of floating button, instead of the announce block at the top of the page? This would take some CSS trickery for the custom floating button, and some trial and error to get the right look 🤔. I'm also not so sure it would look better than the current setup, but if the time allows, I'll play around with it over the coming week or so.

**Comment by Andygol** [comment]
Info toggle button in the header looks good to me, so there is no extra need to make it "float". It may be good to make float info dialog instead of using Announce bar on the top. What you think? 

There is no deadline at all 😀.

**Pull request merged**
